server.port=8080

# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/dropfilex
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123321}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Spring Security
spring.security.user.name=admin
spring.security.user.password=123321

# File Upload Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# OAuth2 Configuration for Google
spring.security.oauth2.client.registration.google.client-id=61397727162-a3cquuur88kocdmjq0sbvlqad03rff1b.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# OAuth2 Configuration for GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23li34HjQEwucygG0O
spring.security.oauth2.client.registration.github.client-secret=ddfc17d604c8b1c1897d89bacfa0e8d61dd3fde1
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github

# OAuth2 Provider Configuration (usually auto-configured, but you can specify if needed)
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://accounts.google.com/o/oauth2/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=id

# Logging
#logging.level.org.springframework=INFO
#logging.level.com.example.FileSharing=DEBUG